name: component_repository
description: A repository to handle component related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.1.0
  async: ^2.9.0
  component_grpc:
    path: ../component_grpc

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
