name: qilletni_frontend
description: Generate infinite, dynamic, and intelligent Spotify queues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  authentication_repository:
    path: ./packages/authentication_repository
  component_repository:
    path: ./packages/component_repository
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
