name: qilletni_frontend
description: Generate infinite, dynamic, and intelligent Spotify queues
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  copy_with_extension: ^4.0.2
  authentication_repository:
    path: ./packages/authentication_repository
  component_repository:
    path: ./packages/component_repository
  component_grpc:
    path: ./packages/component_grpc
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
