name: authentication_repository
description: An API wrapper for external authentication
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  uni_links: ^0.5.1
  url_launcher: ^6.1.4
  uni_links_desktop: ^0.1.2
  http: ^0.13.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
